name: 签到

on:
  #push:
    #branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: 30 16 * * ?
  watch:
    types: started
    
jobs:
  run-it:
    runs-on: ubuntu-latest
    name: 签到
    #if: github.event.repository.owner.id == github.event.sender.id
    steps:
        - name: Checkout codes
          uses: actions/checkout@v2
          
        - name: 运行时间
          run: |
           time=$(curl -s "http://quan.suning.com/getSysTime.do")
           echo -e "当前时间：$(echo "${time}" | awk -F '":"|","' '{print $2}')"
           
    #设置PARAMETER的值为脚本支持的参数,如 githubaction membercenter 13800008888@112233 18388880000@123456
 
        - name: 运行号码签到
          env:
           PARAMETER: ${{ secrets.PARAMETER }}
          run: |
           bash CnUnicom.sh $PARAMETER
